apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: istio-system
  name: account-app-destination-rule
  metadata:
    labels:
      env: {{ .Values.general.env }}
spec:
  exportTo:
    - "*"
  host: account-app-service.microservices.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: DISABLE
