apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: services
  name: orchestrator-app-destination-rule
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "*"
  host: orchestrator-service.microservices.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: DISABLE
